nix-community/nixos-apple-silicon

nix/m1-support/kernel/package.nix

This fixes usage in pure evaluation mode (i.e., flakes) and doesn't affect any existing use-cases.

kernel: Fix pure evaluation

---

nix/m1-support/boot-m1n1/default.nix

This helped me debugging the build as there was no need to build the entire system, just m1n1

Expose m1n1 via system.build

---

nix/m1-support/u-boot/default.nix

`system` is an attribute in `pkgs.stdenv`, not `pkgs`

u-boot: Fix system detection

---

docs/uefi-standalone.md

docs: fix typo

---

nix/m1-support/kernel/default.nix
nix/m1-support/kernel/package.nix

... to make tinkering with the kernel configs and custom patches as simple as following the [wiki](https://nixos.wiki/wiki/Linux_kernel).
I also modified the `readConfig` function a little bit to make it allow config overrides, by basically just build the Nix expression from `//`-ing single-property sets.
Feel free to edit my branch as you need, I might not be around to reply to change requests.

Pass `boot.kernelPatches` to the kernel package

---

docs/uefi-standalone.md
nix/installer-bootstrap/installer-configuration.nix
nix/m1-support/kernel/default.nix
nix/m1-support/m1n1/default.nix
nix/m1-support/u-boot/default.nix

Small fixes and changes:
- Stop caring about the m1n1 mach-o binary
- Add curl, wget, and wormhole-william to the installer environment to make it easier to copy files
- Fix the "Error switching console mode" bug
- Increase the size of the u-boot font, which makes the NixOS generation picker readable
Previous review comments at https://github.com/tpwrules/nixos-m1/pull/32

Improvements 2022-12-2

---

nix/m1-support/peripheral-firmware/default.nix

I think this is correct. This fixes the issue where pkgs.requireFile cannot be used for the firmware directory. The root cause is that ./ + does not work for store paths

peripheral-firmware: Allow using pkgs.requireFile

---

docs/uefi-standalone.md

Some Apple keyboards have the layout set incorrectly. As documented on the [Arch Wiki](https://wiki.archlinux.org/title/Apple_Keyboard), these can be fixed by adding settings to Modprobe (On NixOS,`boot.extraModprobeConfig`). Setting `options hid_apple iso_layout=0` worked on my M2 MacBook Air.
(the force pushes were because I forgot that this PR is merging my main branch, I didn't realize that my subsequent commits would appear here as well, as well as fixing mistakes I added in the process)

add documentation for keyboard layout fix

---

apple-silicon-support/packages/linux-asahi/default.nix
apple-silicon-support/packages/linux-asahi/rust-bindgen-version.patch

Fixes #63 
Depends on #68 
This is certainly not how it _should_ be fixed. The bindgen version detection should ideally be fixed upstream, and the cross-references between `dev` and `out` should be properly addressed. Therefore, I'm not sure if you'll want to merge this. However, I wanted to submit anyway it so that other people could use it in the meantime

Fix Rust in kernel

---

docs/uefi-standalone.md

This confused me very slightly the first time round - it was a little unclear to me whether for some cursed reason I *had* to use a USB-A stick.

Clarify USB instructions in uefi-standalone.md

---

docs/uefi-standalone.md
iso-configuration/installer-configuration.nix

It is better to use iwd instead of wpa_supplicant because the latter [does not support WPA3 on broadcom chips](https://www.reddit.com/r/AsahiLinux/comments/12igyoa/comment/jftvl3c) (which are installed on macs) and in general iwd is more modern, easy to use and maintained then wpa_supplicant.<br>
This PR is a draft because it must be merged at the same time as new release image is uploaded because otherwise it may confuse people who expect iwd to be availible in old installation ISO with wpa_supplicant.

Move away from wpa_supplicant to iwd

---

default.nix
flake.lock
flake.nix

This adds flake-compat, allowing access to the package recipes in here from a Nix without flakes support enabled.
Afterwards, a
`nix-build default.nix -A outputs.packages.aarch64-linux.m1n1` for example works.

flakes: add flake-compat

---

apple-silicon-support/packages/linux-asahi/default.nix

I saw this was changed in the commit, so I thought it might be a mistake. The kernel rejects the patch on Rust 1.69 (latest nixos stable as of today) otherwise.
Build logs
```
applying patch /nix/store/1an7d69g4ig8dnnjxd1488j4l8c6ykn9-rust-1.70.patch
patching file rust/alloc/lib.rs
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file rust/alloc/lib.rs.rej
patching file rust/alloc/vec/into_iter.rs
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
5 out of 5 hunks ignored -- saving rejects to file rust/alloc/vec/into_iter.rs.rej
patching file scripts/Makefile.build
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? …
```

Remove the Rust 1.70 patch

---

apple-silicon-support/packages/linux-asahi/default.nix
apple-silicon-support/packages/linux-asahi/rust_1_71_0.patch

Rust 1.71 is currently in staging-next.
I went through the errors and copied together the resolutions from https://github.com/Rust-for-Linux/linux/commit/327cfb66df6947db1618ec0dd339648b0db258e7 and https://github.com/Rust-for-Linux/linux/commit/6abe8c9688d6033f1d5cde1c0468e363602a7a1e

add patch for rust 1.71

---

apple-silicon-support/modules/mesa/default.nix

When `pkgs` is passed to `nixosSystem` directly, the `nixpkgs.overlays` option doesn't do anything.

Support flakes that pass `pkgs` to `nixosSystem`

---

apple-silicon-support/packages/m1n1/default.nix

This fixes brightness control on a M1 MacBook Air and possibly other devices.
Based on https://github.com/AsahiLinux/PKGBUILDs/commit/f96d51311473b2e6073fbc003d0838f299b1ec6b

m1n1: 1.2.9 -> 1.3.3

---

apple-silicon-support/packages/alsa-ucm-conf-asahi/default.nix
apple-silicon-support/packages/overlay.nix

This adds the package so that headphones volume work by overriding the upstream alsa-ucm-conf and copying the extra asahi ucm2 confs into destination folder
Not entirely sure how package should be added for default installation in modules

alsa-ucm-conf-asahi: Add support for audio confs

---

apple-silicon-support/packages/linux-asahi/default.nix
apple-silicon-support/packages/linux-asahi/rustc-1.73.0-fix.patch

Needed for rustc 1.73.0 which is currently in staging-next.
The patch is authored by me. This time around the patch is a bit more involved/hacky. An attempt at an explanation:
rust-next already has a patch for 1.73.0, but rust-next does not contain the driver module of the kernel crate, because that is not yet upstreamed to mainline.
The const_impl unstable feature is being reworked, and I could not make it work, got several compiler panics on the way.
Because the affected RawDeviceId trait is currently only implemented for one single struct, we can just manually insert this DeviceId struct in all the places where RawDeviceId was used as a generic, circumventing the use of const_trait.

rust 1.73.0 patch

---

apple-silicon-support/modules/kernel/default.nix

I spent a bit too much time debugging why Central Scrutinizer wasn't working immediately with NixOS, turns out it was this baud rate. Notably it differs from what the rest of boot uses, so I think it should match the defaults for those parts. Unfortunately Central Scrutinizer isn't configurable, so if we set everything else to 1.5M it would not work by default.

Use 115200n8 for serial console to match what early boot (m1n1, u-boot, etc.) is using and what the Central Scrutinizer expects.

---

apple-silicon-support/packages/linux-asahi/config

Closes https://github.com/tpwrules/nixos-apple-silicon/issues/126
A hacky fix for now since you normally shouldn't manually write into it like this. But at the very least this makes it work until the config is properly synchronized. I tried to find the Fedora config but I don't know where it is.

linux-asahi: Add CONFIG_MUX_APPLE_DPXBAR

---

apple-silicon-support/packages/linux-asahi/default.nix
apple-silicon-support/packages/mesa-asahi-edge/default.nix

For more information, see [Conformant OpenGL 4.6 on the M1](https://rosenzweig.io/blog/conformant-gl46-on-the-m1.html). This updates to the latest asahi-linux kernel tag as well as the latest mesa-asahi-edge tag.
Works on my machine™ (m1 pro).
This allows blender and other tools to run.

Update kernel and mesa to support OpenGL 4.6

---

apple-silicon-support/packages/linux-asahi/default.nix

Contains a fix for the dm-crypt corruption issue, rather than reverts.
Fixes https://github.com/tpwrules/nixos-apple-silicon/issues/200.

linux-asahi: asahi-6.8.9-6 -> asahi-6.8.9-7

---

docs/uefi-standalone.md

Both nixpkgs master and stable provide sufficiently up-to-date versions.
Rework the section as suggested in
https://github.com/tpwrules/nixos-apple-silicon/pull/188#issuecomment-2067804783.
Closes #188.

docs/uefi-standalone: update idevicerestore/usbmuxd instructions

---

apple-silicon-support/modules/mesa/default.nix

This PR prevents weird behavior when cross compiling to other architectures and mesa is wanted.

mesa: fix cross compiling

---

apple-silicon-support/packages/mesa-asahi-edge/vendor/default.nix

This fixes the build with current nixos-unstable. 
See https://github.com/NixOS/nixpkgs/pull/338337

mesa: Upstream removed lib.platforms.mesaPlatforms

---

apple-silicon-support/modules/default.nix

That's the only released version accessible in nixpkgs that exposed this issue.
It's fixed in 256.8, which is already in nixpkgs staging.
If we unconditionally apply it for all later versions, the pach will fail to apply and due to this fail the build.

systemd: only apply boot fix patch for 256.7

---

apple-silicon-support/modules/mesa/default.nix

`system.replaceRuntimeDependencies` has been renamed in NixOS to `system.replaceDependencies.replacements`.
This PR fixes that to stop warnings when rebuilding the system.

Rename `system.replaceRuntimeDependencies` -> `system.replaceDependencies.replacements`

---

apple-silicon-support/modules/sound/default.nix

fix for https://github.com/tpwrules/nixos-apple-silicon/issues/270

lsb-plugins: don't override php anymore

---

apple-silicon-support/modules/sound/default.nix

Rebuilding yielded the non-fatal warning:
```
evaluation warning: The option `hardware.pulseaudio' defined in `/nix/store/s0l0z3zlkzb4fxzlv26g2nhqbdgkl250-source/apple-silicon-support/modules/sound' has been renamed to `services.pulseaudio'.
```
Changed config hardware.pulseaudio to services.pulseaudio.
This change silenced the warning on my M1 MacBook Air. [My config](https://github.com/azaleacolburn/flake).
~~Unfortunately, I couldn't find any documentation on this change, and [the pulse audio nixos documentation](https://nixos.wiki/wiki/PulseAudio) still lists it as `hardware.pulseaudio`, so I understand if this PR gets closed. Although, perhaps that's a separate config and I'm confusing the two.~~
EDIT: [Updated Documentation](https://wiki.nixos.org/wiki/PulseAudio) which explains …

Update Pulseaudio Option 

---

apple-silicon-support/packages/linux-asahi/default.nix

The former doesn't build with rustc 1.85, which is what's landed in nixpkgs.

linux-asahi: 6.12.12-asahi -> 6.13.5-asahi

---

apple-silicon-support/modules/mesa/default.nix
apple-silicon-support/packages/mesa-asahi-edge/default.nix
apple-silicon-support/packages/mesa-asahi-edge/system-gbm.patch

After https://github.com/NixOS/nixpkgs/pull/387292 mesa.drivers became deprecated and now points to the nixpkgs mesa which means that asahi-mesa is not used even if experimental driver is enabled.

use mesa instead of the deprecated mesa.drivers

---

apple-silicon-support/packages/m1n1/default.nix
flake.lock
flake.nix

Since some time now, nixpkgs has the "fastCross" path for rebuilding only the rust std/core libraries for an additional target and create a wrapper pointing to it as a sysroot. So we can make use of this infrastructure to very quickly (~1min on M1 Pro) build a rustc for the appropriate target.

use nixpkgs rust cross toolchain for m1n1

---

apple-silicon-support/modules/kernel/default.nix

**What?**
This PR removes the serial console parameter from the kernel commandline
**Why?**
1. This causes plymouth to break. I don't know why it is so, but it is so. This PR would fix issue #257 (which I was also struggling with)
2. It's a little unnecessary. It's not core to getting NixOS to boot and work well (which I assume is the goal of this repo), and if a user wants the serial functionality, they can always add it back in their own NixOS configuration (much easier to add after the fact than trying to apply a patch/overlay something onto this repo to remove the kernel parameter without forking)

Remove serial console commandline

---

flake.nix

This commit allows for `nix flake check` `nix flake show` to pass.
Fixes issue #321.
Ensure that `nix flake check` and `nix flake show` are able to display all attributes correctly.
``` shellsession
$ nix flake show --all-systems
├───nixosModules
│   ├───apple-silicon-support: NixOS module
│   └───default: NixOS module
├───overlays
│   ├───apple-silicon-overlay: Nixpkgs overlay
│   └───default: Nixpkgs overlay
└───packages
├───aarch64-linux
│   ├───asahi-audio: package 'asahi-audio-3.3'
│   ├───asahi-fwextract: package 'asahi-fwextract-0.7.8'
│   ├───installer-bootstrap: package 'nixos-25.11.20250528.96ec055-aarch64-linux.iso'
│   ├───linux-asahi: package 'linux-6.14.8-asahi'
│   ├───m1n1: package 'm1n1-1.4.21'
│   ├───mesa-asahi-edge: package 'mesa-25.1.0-asahi'
│   └───uboot-asahi: …
```

flake: expose `linux-asahi` properly

---

.git-blame-ignore-revs
apple-silicon-support/modules/boot-m1n1/default.nix
apple-silicon-support/modules/default.nix
apple-silicon-support/modules/kernel/default.nix
apple-silicon-support/modules/mesa/default.nix
apple-silicon-support/modules/peripheral-firmware/default.nix
apple-silicon-support/modules/sound/default.nix
apple-silicon-support/packages/alsa-ucm-conf-asahi/default.nix
apple-silicon-support/packages/asahi-audio/default.nix
apple-silicon-support/packages/linux-asahi/default.nix
apple-silicon-support/packages/m1n1/default.nix
apple-silicon-support/packages/mesa-asahi-edge/default.nix
apple-silicon-support/packages/uboot-asahi/default.nix
default.nix
flake.lock
flake.nix
iso-configuration/default.nix
iso-configuration/installer-configuration.nix

Since this is under the `nix-community` banner, this project should decide on a formatter. This PR currently chooses `nixfmt-rfc-style` via `github:numtide/treefmt-nix` flake, formats all files, and adds a `.git-blame-ignore-revs` file to ignore this mass reformat when blaming.
This would also allow for pre-commit hooks for formatting all files as well as automatic merge checks when opening additional PRs which reduces the chance of merge conflicts occurring.

treewide: introduce formatter

---

.git-blame-ignore-revs
apple-silicon-support/packages/alsa-ucm-conf-asahi/default.nix
apple-silicon-support/packages/linux-asahi/default.nix
apple-silicon-support/packages/m1n1/default.nix
apple-silicon-support/packages/mesa-asahi-edge/default.nix
flake.lock
iso-configuration/installer-configuration.nix

Brings us to the latest and greatest nixos-unstable.
Tested that the installer boots; had to fix it up a bit.
Also had to reformat now that `nix-fmt` has updated.

update flake inputs

---

README.md
docs/release-notes.md
docs/uefi-standalone.md
flake.lock

A bit embarrassed that the last release was broken. This fixes it. Also updates nixpkgs to lock in some fixes there.
Tested on 2020 Macbook Pro 15" M1 Max that it builds, boots, and installs. Using a Plasma 6 desktop environment. Functioning graphics and sound. I haven't identified any issues.

release 2025-08-23
